FROM golang:latest as builder
WORKDIR /build

ENV GO111MODULE=on

COPY *.go ./
COPY go.mod ./
RUN go get
RUN go build -o psql_drive_state ./psql_drive_state.go
RUN go build -o quarkdb_probe ./quarkdb_probe.go


FROM ghcr.io/cloudprober/cloudprober:latest
RUN apk add libc6-compat
RUN mkdir /root/cta-cloudprober/
COPY --from=builder /build/psql_drive_state /root/cta-cloudprober/psql_drive_state
COPY --from=builder /build/quarkdb_probe /root/cta-cloudprober/quarkdb_probe
